= On technology: lecture notes, examples, and projects
//:repoducible:
//:source-highlighter: coderay
//:listing-caption: Listing
//:pdf-page-size: A4
//:docinfo: private-head
//:idprefix:
//:idseparator: -
//:sectanchors:
//:sectlinks:
:toc:   // gets a ToC after the title
:toc-title: Contents
:toclevels: 4
:sectnums: // gets ToC sections to be numbered
:sectnumlevels: 3

== Hardware

Basic requirements: thin & flat, non-glossy screen

- Lenovo Think pad
- Dell
- HP
- why no more MSF
- bootable usb keys

== Systems
- Debian, ubuntu, linux Mint
- Fedora, Centos
- Windows 10, windows 7
- gparted
- clonezilla

== bash

== python
=== Training suggestions
https://training.talkpython.fm/courses/explore_100days_in_python/100-days-of-code-in-python#course_outline

== javascript

== Text editors
- emacs
- vim

== IDE, Integrated Development Environments
- pycharm
https://training.talkpython.fm/courses/explore_pycharm/mastering-pycharm-ide
- VSCode

== Text editing with  a lightweight markup language

=== Selecting a lightweight markup language
Mainly to rapidly key-in notes that include text, pics, weblinks,

but also tables, cross-references (sharing the same xml:id attribute), footnotes, embedded videos

and also description lists, admonitions (tips, notes, warnings, cautions, etc.) and table of contents.

A cool tip: Github render as html on account head page the https://github/account/account/README.md file. README.adoc will work as well.

AsciiDoc is presented as superior by many, in the context of this page mainly for its Table Of Contents, toc. It is also presented as simpler to grasp. Here is the rationale: https://asciidoctor.org/docs/user-manual/#graduating-to-asciidoc

Markdown & GFM, Github Flavored Markdown: the de facto reference, mainly for Github and Jupyter notebooks.

Rendering on linux Mint:
`sudo apt install retext`
`retext --preview filename.md`

HackMD, mainly for collaborative work on github.  Can draw simple UML diagrams (workflows) and math formulas.

=== AsciiDoctor tutorial

https://AsciiDoctor.org/docs/asciidoc-syntax-quick-reference/

=== Editing asciidoc

==== Cheat sheet

===== Paragraphs

====== Normal

Newlines within a Normal paragraph are not displayed.  Neither are spaces: there are 4 spaces between a    and b.

====== Literal

A paragraph offset by at least one space becomes literal.

 The text is shown in a fixed-width font.
 Spaces and newlines,
 like the ones between a     and b,
 are preserved.

==== Admonition

NOTE: An admonition paragraph draws the reader's attention to auxiliary information.

TIP: Pro tip...

IMPORTANT: Don't forget...

WARNING: Watch out for...

CAUTION: Ensure that...

==== Advanced

==== May be needed one day

=== Rendering AsciiDoctor on linux
`sudo apt install AsciiDoctor`
`AsciiDoctor filename.adoc` will create filename.html in the same directory

=== Convert AsciiDoc to PDF
Simple: print filename.html to pdf. Resulting pdf will have no TOC.

Direct conversion: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

Interesting, also because it unveils PDF'specificities: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc 



