= On technology: lecture notes, examples, and projects
// writing comments after settings is not caught by the linter, but it does not work either ... // don't do it
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
//:repoducible:
//:source-highlighter: coderay
//:listing-caption: Listing
//:pdf-page-size: A4
//:docinfo: private-head
//:idprefix:
//:idseparator: -
//:sectanchors:
//:sectlinks:
//:quick-uri: http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
:toc:   // gets a ToC after the title
:toc-title: Contents
:toclevels: 3
:sectnums: // gets ToC sections to be numbered
:sectnumlevels: 6
//:icons: font	// gets admonition paragraphs to use Font Awesome

== Using Github

 Sort (seiri 整理): check if posted info & content are useful, remove when it's not
 Set in order (seiton 整頓): arrange for easy readability & use
 Shine (seiso 清掃): review periodically for validity (with software updates, the possibility of using system & machine may vary) and to refresh in reader's memory
 Standardize (seiketsu 清潔): standardize look, nomenclature to be more intuitive
 Sustain/self-discipline (shitsuke しつけ): seek & maintain continuous improvement, delivery, deployment

=== Tools

GitHub desktop: to manage a local version

== Hardware

Github is the current repository for several machines:

- A desktop running Linux Mint 20 Ulyuana / Cinnamon
- A Microsoft Surface Book version 1 with double boot: Linux Mint / Cinnamon & Windows 10
- 2 64gb bootable disks, booting Linux Mint / Cinnamon and hopefully one day Windows 10 as well

A Windows 10 VMWare client in Linux Mints allows handling of a few situations that Linux does not, such as:

- Downloading Huawei phone pics & vids
- Connecting to icbc site in China, which can only be browsed with IE
- Running Wenlin with sounds
- Getting TV mp4 from captvty

But cannot
- get the mike sound from RosettaStone, so would need a double boot just for this
- Connect to bluetooth devices.  Watching a movie from Shunlei (BaiduYun can be seen on Linux) with external speakers
would require usb cable.

=== Next laptop basic requirements:
- thin & flat: to work as a e-book
- non-glossy screen: don't see the point of glossy, just annoying
- non HiDPI, don't see the point, lot's of apps can't handle it either
- no more MSF computers: on Windows, drivers were always being updated, as if they would never work
- Lenovo Think pad: probably the best deal in China
- Dell
- HP

== Systems
- Linux Mint is most user friendly
- Fedora, Centos: one day
- gparted: has a superb selection of software, all running in RAM in a ZFS partition
- clonezilla: to make complete machine backups
- Windows 10, windows 7: one day might be needed


== bash

== python
=== Training suggestions
https://training.talkpython.fm/courses/explore_100days_in_python/100-days-of-code-in-python#course_outline

== javascript

== Text editors
- emacs
- vim

== IDE, Integrated Development Environments
- pycharm
https://training.talkpython.fm/courses/explore_pycharm/mastering-pycharm-ide
- VSCode

== Text editing with  a lightweight markup language

=== Selecting a lightweight markup language
Mainly to rapidly key-in notes that include text, pics, weblinks,

but also tables, cross-references (sharing the same xml:id attribute), footnotes, embedded videos

and also description lists, admonitions (note, tip, important, warning, caution) and table of contents.

A cool tip: Github render as html on account head page the https://github/account/account/README.md file. README.adoc will work as well.

AsciiDoc is presented as superior by many, in the context of this page mainly for its Table Of Contents, toc. It is also presented as simpler to grasp. Here is the rationale: https://asciidoctor.org/docs/user-manual/#graduating-to-asciidoc

Markdown & GFM, Github Flavored Markdown: the de facto reference, mainly for Github and Jupyter notebooks.

Rendering on linux Mint:
`sudo apt install retext`
`retext --preview filename.md`

HackMD, mainly for collaborative work on github.  Can draw simple UML diagrams (workflows) and math formulas.

=== AsciiDoctor tutorial

some examples:
 https://github.com/asciidoctor/asciidoctor/blob/master/README.adoc
 https://raw.githubusercontent.com/asciidoctor/asciidoctor/master/README.adoc

https://AsciiDoctor.org/docs/asciidoc-syntax-quick-reference/

=== Editing asciidoc

==== Cheat sheet

===== Paragraphs

====== Normal

Newlines within a Normal paragraph are not displayed.  Neither are spaces: there are 4 spaces between a    and b.

====== Literal

A paragraph offset by at least one space becomes literal.

 The text is shown in a fixed-width font.
 Spaces and newlines,
 like the ones between a     and b,
 are preserved.

===== Admonition

NOTE:  NOTE: An admonition paragraph draws the reader's attention to auxiliary information.

TIP:  TIP: $ sudo apt install fonts-font-awesome   # to render icons

WARNING:  WARNING: Watch out for...

CAUTION:  CAUTION: Ensure that...

IMPORTANT:  IMPORTANT: Don't forget...

====== Inline icons

icon:tags[] ruby, asciidoctor

====== next

==== Advanced

===== Todo
Review https://plugins.jetbrains.com/plugin/7391-asciidoc/reviews

==== May be needed one day

=== Rendering AsciiDoctor on linux
`sudo apt install AsciiDoctor`
`AsciiDoctor filename.adoc` will create filename.html in the same directory

=== Convert AsciiDoc to PDF
Simple: print filename.html to pdf. Resulting pdf will have no TOC.

Direct conversion: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

Interesting, also because it unveils PDF'specificities: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc 

== Major techs

=== Linux

=== VIM

 :scriptnames  " to see what files & plugins are loaded at startup

 :new
 :put=execute('scriptnames')  " will write in the new file

 VSCode will check in Settings (Ctrl+comma)  Vim> Vimrc:Path for vimrc file

=== Architecture / Gang of 4

=== Dockers

=== Git

=== Python

=== JavaScript / TypeScript / 

=== Postgresql

== Other techs 

=== Inkscape

=== VSCode

==== VSCode install

===== VSCode Settings Sync

Settings Sync lets you share your Visual Studio Code configurations such as settings, keybindings, and installed extensions across your machines so you are always working with your favorite setup.

The Turn On Settings Sync entry is in the Manage gear menu at the bottom of the Activity Bar (vertical left bar).  This will synchronize:

- Settings
- Keyboard shortcuts for each platform
- User snippets
- Extensions
- UI state


===== Default clone directory

 User settings 'CTRL + comma'  /  enter the path to your desired directory with slashes:
 "git.defaultCloneDirectory": "~/Documents/GitHub/"

=== asciiDoctor

== Testing techs