= On technology: lecture notes, examples, and projects

:ahjun001-medi-base: https://raw.githubusercontent.com/ahjun001/ahjun001/master/
:repoducible:
:source-highlighter: coderay
:listing-caption: Listing
:pdf-page-size: A4
:docinfo: private-head
:idprefix:
:idseparator: -
:sectanchors:
:sectlinks:
:sectnumlevels: 6
:sectnums:
:toc: macro
:toclevels: 6
:toc-title:

toc::[]


== Hardware

Basic requirements: thin & flat, non-glossy screen

- Lenovo Think pad
- Dell
- HP
- why no more MSF
- bootable usb keys

== Systems
- Debian, ubuntu, linux Mint
- Fedora, Centos
- Windows 10, windows 7
- gparted
- clonezilla

== bash

== python

== javascript

== Text editors
- emacs
- vim

== IDE, Integrated Development Environments

== Selecting a lightweight markup language
Mainly to rapidly key-in notes that include text, pics, weblinks,

but also tables, cross-references (sharing the same xml:id attribute), footnotes, embedded videos

and also description lists, admonitions (tips, notes, warnings, cautions, etc.) and table of contents.

A cool tip: Github render as html on account head page the https://github/account/account/README.md file. README.adoc will work as well.

AsciiDoc is presented as superior by many, in the context of this page mainly for its Table Of Contents, toc. It is also presented as simplier to grasp. Here is the rationale: https://asciidoctor.org/docs/user-manual/#graduating-to-asciidoc

Markdown & GFM, Github Flavored Markdown: the de facto reference, mainly for Github and Jupyter notebooks.

Rendering on linux Mint:
`sudo apt install retext`
`retext --preview filename.md`

HackMD, mainly for collaborative work on github.  Can draw simple UML diagrams (workflows) and math formulas.

== AsciiDoctor tutorial
https://AsciiDoctor.org/docs/asciidoc-syntax-quick-reference/

=== Editing asciidoc
==== Cheat sheet

==== Advanced

==== May be needed one day

=== Rendering AsciiDoctor on linux
`sudo apt install AsciiDoctor`
`AsciiDoctor filename.adoc` will create filename.html in the same directory

=== Convert AsciiDoc to PDF
Simple: print filename.html to pdf. Resulting pdf will have no TOC.

Direct conversion: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

Interesting, also because it unveils PDF'specificities: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc 



