= On technology: lecture notes, examples, and projects
// writing comments after settings is not caught by the linter, but it does not work either ... // don't do it
ifndef::env-github[:icons: font]
ifdef::env-github[]
:status:
:outfilesuffix: .adoc
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]
//:repoducible:
//:source-highlighter: coderay
//:listing-caption: Listing
//:pdf-page-size: A4
//:docinfo: private-head
//:idprefix:
//:idseparator: -
//:sectanchors:
//:sectlinks:
//:quick-uri: http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/
:toc:   // gets a ToC after the title
:toc-title: Contents
:toclevels: 3
:sectnums: // gets ToC sections to be numbered
:sectnumlevels: 6
//:icons: font	// gets admonition paragraphs to use Font Awesome

== Using Github

For each technology, maintain a cheatsheet, personal or outsourced, that points out to what responses to typical situations should be, backed with sources, illustrated with examples.

=== Maintain 5S
 Sort (seiri 整理): check if posted info & content are useful, remove when it's not
 Set in order (seiton 整頓): arrange for easy readability & use
 Shine (seiso 清掃): review periodically for validity (with software updates, the possibility of using system & machine may vary) and to refresh in reader's memory
 Standardize (seiketsu 清潔): standardize look, nomenclature to be more intuitive
 Sustain/self-discipline (shitsuke しつけ): seek & maintain continuous improvement, delivery, deployment

=== Have a local copy of GitHub repositories under the same directory:

In settings.json (ctrl+comma):

 "git.defaultCloneDirectory": "~/Documents/GitHub/",

=== Tools

GitHub desktop: to manage a local version

== Hardware

Github is the current repository for several machines:

- A desktop running Linux Mint 20 Ulyuana / Cinnamon
- A Microsoft Surface Book version 1 with double boot: Linux Mint / Cinnamon & Windows 10
- 2 64gb bootable disks, booting Linux Mint / Cinnamon and hopefully one day Windows 10 as well

A Windows 10 VMWare client in Linux Mints allows handling of a few situations that Linux does not, such as:

- Downloading Huawei phone pics & vids
- Connecting to icbc site in China, which can only be browsed with IE
- Running Wenlin with sounds
- Getting TV mp4 from captvty

But cannot
- get the mike sound from RosettaStone, so would need a double boot just for this
- Connect to bluetooth devices.  Watching a movie from Shunlei (BaiduYun can be seen on Linux) with external speakers
would require usb cable.

=== Next laptop basic requirements:
- thin & flat: to work as a e-book
- non-glossy screen: don't see the point of glossy, just annoying
- non HiDPI, don't see the point, lot's of apps can't handle it either
- no more MSF computers: on Windows, drivers were always being updated, as if they would never work
- Lenovo Think pad: probably the best deal in China
- Dell
- HP

== Systems
- Linux Mint is most user friendly
- Fedora, Centos: one day
- gparted: has a superb selection of software, all running in RAM in a ZFS partition
- clonezilla: to make complete machine backups
- Windows 10, windows 7: one day might be needed


== bash

== python
=== Training suggestions
https://training.talkpython.fm/courses/explore_100days_in_python/100-days-of-code-in-python#course_outline

== javascript

== Text editors
- emacs
- vim

== IDE, Integrated Development Environments
- pycharm
https://training.talkpython.fm/courses/explore_pycharm/mastering-pycharm-ide
- VSCode

== Text editing with  a lightweight markup language

=== Selecting a lightweight markup language
Mainly to rapidly key-in notes that include text, pics, weblinks,

but also tables, cross-references (sharing the same xml:id attribute), footnotes, embedded videos

and also description lists, admonitions (note, tip, important, warning, caution) and table of contents.

A cool tip: Github render as html on account head page the https://github/account/account/README.md file. README.adoc will work as well.

AsciiDoc is presented as superior by many, in the context of this page mainly for its Table Of Contents, toc. It is also presented as simpler to grasp. Here is the rationale: https://asciidoctor.org/docs/user-manual/#graduating-to-asciidoc

Markdown & GFM, Github Flavored Markdown: the de facto reference, mainly for Github and Jupyter notebooks.

Rendering on linux Mint:
`sudo apt install retext`
`retext --preview filename.md`

HackMD, mainly for collaborative work on github.  Can draw simple UML diagrams (workflows) and math formulas.

=== AsciiDoctor tutorial

some examples:
 https://github.com/asciidoctor/asciidoctor/blob/master/README.adoc
 https://raw.githubusercontent.com/asciidoctor/asciidoctor/master/README.adoc

https://AsciiDoctor.org/docs/asciidoc-syntax-quick-reference/

=== Editing asciidoc

==== Cheat sheet

===== Paragraphs

====== Normal

Newlines within a Normal paragraph are not displayed.  Neither are spaces: there are 4 spaces between a    and b.

====== Literal

A paragraph offset by at least one space becomes literal.

 The text is shown in a fixed-width font.
 Spaces and newlines,
 like the ones between a     and b,
 are preserved.

===== Admonition

NOTE:  NOTE: An admonition paragraph draws the reader's attention to auxiliary information.

TIP:  TIP: $ sudo apt install fonts-font-awesome   # to render icons

WARNING:  WARNING: Watch out for...

CAUTION:  CAUTION: Ensure that...

IMPORTANT:  IMPORTANT: Don't forget...

====== Inline icons

icon:tags[] ruby, asciidoctor

====== next

==== Advanced

===== Todo
Review https://plugins.jetbrains.com/plugin/7391-asciidoc/reviews

==== May be needed one day

=== Rendering AsciiDoctor on linux
`sudo apt install AsciiDoctor`
`AsciiDoctor filename.adoc` will create filename.html in the same directory

=== Convert AsciiDoc to PDF
Simple: print filename.html to pdf. Resulting pdf will have no TOC.

Direct conversion: https://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

Interesting, also because it unveils PDF'specificities: https://github.com/asciidoctor/asciidoctor-pdf/blob/master/docs/theming-guide.adoc 

== Major techs

=== Linux

=== Forgotten commands

 sudo update-alternatives --install /usr/bin/editor editor /usr/local/bin/vim 100

==== Linux Mint 20 on MS Surface book

After install new kernel, check updates on https://github.com/linux-surface/linux-surface/issues/96 

=== VIM

https://github.com/ahjun001/cheat-sheet_VIM

=== Architecture / Gang of 4

=== Dockers

=== Git

https://kamranahmed.info/blog/2015/07/20/random-git-tips-and-tricks/

==== Updating a fork

https://www.earthdatascience.org/courses/intro-to-earth-data-science/git-github/github-collaboration/update-github-repositories-with-changes-by-others/#:~:text=You%20can%20update%20your%20fork,be%20updated%20in%20your%20fork.

https://levelup.gitconnected.com/how-to-sync-forked-repositories-using-git-or-github-2933e497fa16


=== Python

==== Podcasts which are worth a listen

 https://pythonbytes.fm/episodes/all
 https://talkpython.fm/episodes/all
 https://realpython.com/podcasts/rpp/


=== JavaScript / TypeScript / 

=== Postgresql

== Other techs 

=== Inkscape

=== VSCode

==== VSCode install

===== VSCode Settings Sync

Settings Sync lets you share your Visual Studio Code configurations such as settings, keybindings, and installed extensions across your machines so you are always working with your favorite setup.

The Turn On Settings Sync entry is in the Manage gear menu at the bottom of the Activity Bar (vertical left bar).  This will synchronize:

- Settings
- Keyboard shortcuts for each platform
- User snippets
- Extensions
- UI state


===== Default clone directory

 User settings 'CTRL + comma'  /  enter the path to your desired directory with slashes:
 "git.defaultCloneDirectory": "~/Documents/GitHub/"

=== asciiDoctor


=== Astrill

==== Site filter

 smtp.263.net
 imap.263.net
 https://partner.outlook.cn/
 https://portal.partner.microsoftonline.cn/
 https://login.partner.microsoftonline.cn/
 https://www.system-in-motion.com/
 https://web.wechat.com/
 https://www.wechat.com/
 https://www.baidu.com/
 https://company.zhaopin.com/
 http://mirrors.cn99.com/
 59.111.0.251
 http://mirrors.aliyun.com/ubuntu/
 https://mirrors.bfsu.edu.cn/
 39.155.141.16
 http://mirrors.ustc.edu.cn/
 http://archive.canonical.com/
 http://security.ubuntu.com/
 https://dl.winehq.org/wine-builds/
 

=== Roadmaps

 https://andreasbm.github.io/web-skills/?compact
 https://roadmap.sh/


== Testing techs


== Interesting programmers

Most active Github users: https://gist.github.com/paulmillr/2657075

Ciro S.: posix-ubuntu, python, bonne appréciation de l'environment du software (free-lance system engineers will find it difficult against big corps), de la Chine.

Russell Keith-Magee: for its views on open-source. https://realpython.com/podcasts/rpp/22/

Armin Ronacher: created Flask as an April's fool joke. https://realpython.com/podcasts/rpp/18/

Brett Cannon: Python core developer https://pythonbytes.fm/episodes/show/191/live-from-the-manning-python-conference

Conor Hoekstra: https://talkpython.fm/episodes/show/275/beautiful-pythonic-refactorings

William Stein: https://talkpython.fm/episodes/show/273/cocalc-a-fully-colloborative-notebook-development-environment

Ravin Kumar: https://talkpython.fm/episodes/show/270/python-in-supply-chains-oil-rigs-rockets-and-lettuce


Karan Ahmed: for his roadmaps (frontend, backend, devops)

 https://github.com/kamranahmedse
 http://youtube.com/theroadmap
 Design Patterns: https://roadmap.sh/guides/design-patterns-for-humans
 Interesting suggestions: https://kamranahmed.info/
 Monitoring git updates: https://github.com/kamranahmedse/git-standup

Andrei Cioara: for his suggestions on organizing GitHub, Gitlab, and BitBucket repos, https://github.com/aicioara

HFT Guy in London, on how to organize GitHub repos: https://thehftguy.com/2016/10/24/heres-how-to-make-a-good-github-project-for-your-resume/

Sindre Sorhus, for 1k+ repositories on Github: https://github.com/sindresorhus?tab=repositories

== Interesting programs

